receivers:
  opencensus:
    endpoint: 0.0.0.0:55678

  zipkin:
    endpoint: 0.0.0.0:9411

  jaeger:
    protocols:
      grpc:
      thrift-http:
      thrift-tchannel:
      thrift-compact:
      thrift-binary:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889


  logging:


  jaeger_grpc:
    endpoint: jaeger-collector.monitoring-stack.svc.cluster.local:14250

# Alternatively, use jaeger_thrift_http with the settings below. In this case
# update the list of exporters on the traces pipeline.
#
#  jaeger_thrift_http:
#    url: http://jaeger-collector.monitoring-stack.svc.cluster.local:14268/api/traces

processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [opencensus, jaeger, zipkin]
      exporters: [logging, jaeger_grpc]
      processors: [batch, queued_retry]
    metrics:
      receivers: [opencensus]
      exporters: [logging, prometheus]

