apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: almond

spec:
  serviceName: almond
  template:
    spec:
      containers:
      - name: almond
        command: [
          "start-notebook.sh",
          "--NotebookApp.base_url=/jupyter",
          "--NotebookApp.password=sha1:8ada89c23fb7:887a5e9faf47468fecc976c81d8e0b29db8da538" # = "myPasswordDamnIt" Env var substitution does not seems to work here 
        ]
  volumeClaimTemplates:
  - metadata:
      name: almond-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "local-path"
      resources:
        requests:
          storage: 1Gi
