apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: tracing-cluster

spec:
  kafka:
    replicas: 2
    jvmOptions:
      -Xms: "512M"
      -Xmx: "512M"
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 2Gi
        cpu: 100m

  zookeeper:
    replicas: 1
    jvmOptions:
      -Xms: "256M"
      -Xmx: "256M"
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 100m

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: tracing-cluster

spec:
  replicas: 2
  jvmOptions:
    -Xms: "256M"
    -Xmx: "256M"
  resources:
    limits:
      memory: 1Gi
      cpu: "2"
    requests:
      memory: 1Gi
      cpu: "500m"
