apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j

spec:
  template:
    spec:
      containers:
      - name: neo4j
        resources:
          requests:
            cpu: "500m"
            memory: "6Gi"
          limits:
            cpu: "2"
            memory: "8Gi"
        env:
        - name: NEO4J_AUTH
          value: none
        - name: NEO4J_dbms_memory_heap_initial__size
          value: 2G
        - name: NEO4J_dbms_memory_heap_max__size
          value: 2G
        - name: NEO4J_dbms_memory_pagecache_size
          value: 2G
        - name: NEO4J_dbms_tx__log_rotation_retention__policy
          value: 2 days
  volumeClaimTemplates:
  - metadata:
      name: "neo4j-data"
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "local-path"
      resources:
        requests:
          storage: 20Gi
