---
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    editable: false
    access: proxy
    orgId: 1
    url: http://prometheus:9090/prometheus
    isDefault: true
    timeInterval: "15s"