apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: neo4j
  namespace: trace-grapher
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
  - http:
      paths:
      - path: /browser(/|$)(.*)
        backend:
          serviceName: neo4j
          servicePort: web
      - path: /db(/|$)(.*)
        backend:
          serviceName: neo4j
          servicePort: web


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  7687: "trace-grapher/neo4j:7687"
