apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tracegrapher-tier: monitoring-k8s

namespace: trace-grapher

configMapGenerator:
  - name: filebeat-config
    files:
      - filebeat_conf/filebeat.yml
  - name: filebeat-inputs
    files:
      - filebeat_conf/inputs.yml


resources:
  - kibana.yml
  - virtualservice.yml
  - filebeat-rbac.yml
  - filebeat-daemonset.yml
