apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tracegrapher-tier: monitoring-k8s

namespace: trace-grapher

configMapGenerator:
  - name: filebeat-config
    files:
      - filebeat_conf/filebeat.yml
  - name: filebeat-inputs
    files:
      - filebeat_conf/inputs.yml
  - name: metricbeat-daemonset-config
    files:
      - metricbeat_daemonset_conf/metricbeat.yml
  - name: metricbeat-daemonset-modules
    files:
      - metricbeat_daemonset_conf/kubernetes.yml
      - metricbeat_daemonset_conf/system.yml
  - name: metricbeat-deployment-config
    files:
      - metricbeat_deployment_conf/metricbeat.yml
  - name: metricbeat-deployment-modules
    files:
      - metricbeat_deployment_conf/kubernetes.yml


resources:
  - kibana.yml
  - virtualservice.yml
  - filebeat-rbac.yml
  - filebeat-daemonset.yml
  - metricbeat-rbac.yml
  - metricbeat-daemonset.yml
  - metricbeat-deployment.yml
