- module: kubernetes
  metricsets:
    - node
    - system
    - pod
    - container
    - volume
  period: 10s
  host: ${NODE_NAME}
  hosts: ["localhost:10255"]

- module: kubernetes
  metricsets:
    - proxy
  period: 10s
  host: ${NODE_NAME}
  hosts: ["localhost:10249"]