apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterRole.yml
  - clusterRoleBinding.yml
  - daemonset.yml
  - service.yml
  - serviceAccount.yml
  - serviceMonitor.yml
