apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: alertmanager-main
    files:
      - config/alertmanager.yaml

resources:
  - alertmanager.yml
  - service.yml
  - serviceAccount.yml
  - serviceMonitor.yml

