apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
  trafficManagement:
    components:
      pilot:
        k8s:
          replicaCount: 1
          env:
          - name: PILOT_TRACE_SAMPLING
            value: '100.0'
          - name: PILOT_ENABLE_REDIS_FILTER
            value: 'false'
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          hpaSpec:
            minReplicas: 1
            maxReplicas: 1
  gateways:
    enabled: true
    components:
      ingressGateway:
        enabled: true
        k8s:
          replicaCount: 1
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          hpaSpec:
            minReplicas: 1
            maxReplicas: 1
      egressGateway:
        enabled: false
  telemetry:
    enabled: true
    components:
      telemetry:
        k8s:
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          hpaSpec:
            minReplicas: 1
            maxReplicas: 2

  values:
    global:
      enableTracing: true
      controlPlaneSecurityEnabled: false
      k8sIngress:
        enabled: true
        enableHttps: true
        gatewayName: ingressgateway
      proxy:
        tracer: zipkin
      tracer:
        zipkin:
          address: "otel-collector.monitoring-stack.svc.cluster.local:9411"
    sidecarInjectorWebhook:
      enabled: true
      rewriteAppHTTPProbe: false
    pilot:
      traceSampling: 100
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
    mixer:
      policy:
        enabled: true
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
      telemetry:
        enabled: true
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
      adapters:
        stdio:
          enabled: true
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        type: LoadBalancer
        sds:
          enabled: true
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
        ports:
        - name: http2
          port: 80
          targetPort: 80
        - name: https
          port: 443
      istio-egressgateway:
        enabled: true
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
    prometheus:
      enabled: false
    grafana:
      enabled: false
    kiali:
      enabled: false
    tracing:
      enabled: false
