apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
  trafficManagement:
    components:
      pilot:
        k8s:
          env:
          - name: PILOT_ENABLE_REDIS_FILTER
            value: 'false'
  gateways:
    enabled: true
    components:
      ingressGateway:
        enabled: true
        # k8s:
      egressGateway:
        enabled: true
  telemetry:
    enabled: true

  values:
    global:
      enableTracing: true
      proxy:
        tracer: zipkin
      tracer:
        zipkin:
          address: "otel-collector.monitoring-stack.svc.cluster.local:9411"
    pilot:
      traceSampling: 100
    prometheus:
      enabled: false
    grafana:
      enabled: false
    kiali:
      enabled: false
    tracing:
      enabled: false
