---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: jaeger-tracing-backend
spec:
  version: 7.4.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false   # TO DISABLE
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['bash', '-c', 'sysctl -w vm.max_map_count=262144']
            # - name: x-pack
            #   securityContext:
            #     privileged: true
            #   command: ['bash', '-c', 'bin/elasticsearch-plugin remove x-pack']
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPS
                  value: "-Xms1g -Xmx1g"
              resources:
                requests:
                  memory: 2Gi
                  cpu: "500m"
                limits:
                  memory: 2Gi
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: hostpath
...


---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.4.2
  count: 1
  elasticsearchRef:
    name: jaeger-tracing-backend
  http:
    tls:
      selfSignedCertificate:
        disabled: true
...
