---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-cluster-topics-ui
spec:
  selector:
    matchLabels:
      app: tracing-cluster-topics-ui
  template:
    metadata:
      labels:
        app: tracing-cluster-topics-ui
    spec:
      containers:
        - name: tracing-cluster-topics-ui
          image: landoop/kafka-topics-ui
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: KAFKA_REST_PROXY_URL
              value: http://tracing-cluster-bridge-service:8082/
            - name: PROXY
              value: "true"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
...


---
apiVersion: v1
kind: Service
metadata:
  name: tracing-cluster-topics-ui
spec:
  type: ClusterIP
  selector:
    app: tracing-cluster-topics-ui
  ports:
    - name: http
      protocol: "TCP"
      port: 8000
      targetPort: 8000

...


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-cluster-connect-ui
spec:
  selector:
    matchLabels:
      app: tracing-cluster-connect-ui
  template:
    metadata:
      labels:
        app: tracing-cluster-connect-ui
    spec:
      containers:
        - name: kafka-connect-ui
          image: landoop/kafka-connect-ui
          ports:
            - name: http-kc
              containerPort: 8000
          env:
            - name: CONNECT_URL
              value: http://tracing-cluster-connect-api:8083
            - name: PORT
              value: "8000"
            - name: PROXY
              value: "true"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
...


---
apiVersion: v1
kind: Service
metadata:
  name: tracing-cluster-connect-ui
spec:
  type: ClusterIP
  selector:
    app: tracing-cluster-connect-ui
  ports:
    - name: http
      protocol: "TCP"
      port: 8000
      targetPort: 8000
...


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kafka-connect-ui
spec:
  entryPoints:
    - http
    - https
  routes:
    - kind: Rule
      match: 'PathPrefix(`/kafka-connect/`)'
      services:
        - name: tracing-cluster-connect-ui
          port: 8000
      middlewares:
        - name: kafka-tools-strip-ui-prefixes
    - kind: Rule
      match: 'PathPrefix(`/api/kafka-connect-{id:[0-9]+}`)'
      services:
        - name: tracing-cluster-connect-ui
          port: 8000
    - kind: Rule
      match: 'PathPrefix(`/kafka-topics/`)'
      services:
        - name: tracing-cluster-topics-ui
          port: 8000
      middlewares:
        - name: kafka-tools-strip-ui-prefixes
    - kind: Rule
      match: 'PathPrefix(`/api/kafka-rest-proxy/`)'
      services:
        - name: tracing-cluster-topics-ui
          port: 8000
...


---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: kafka-tools-strip-ui-prefixes
spec:
  stripPrefix:
    prefixes:
      - /kafka-connect
      - /kafka-topics
...