# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: tracing-cluster-rest-proxy
# spec:
#   selector:
#     matchLabels:
#       app: tracing-cluster-rest-proxy
#   template:
#     metadata:
#       labels:
#         app: tracing-cluster-rest-proxy
#     spec:
#       ## @TODO Mount secret volume from Strimzi and configure encryption with ZK
#       containers:
#         - name: tracing-cluster-rest-proxy
#           image: confluentinc/cp-kafka-rest:5.3.1
#           ports:
#             - containerPort: 8082
#           env:
#             - name: KAFKA_REST_ZOOKEEPER_CONNECT
#               value: tracing-cluster-zookeeper-client:2181
#             - name: KAFKA_REST_BOOTSTRAP_SERVERS
#               value: PAINTEXT://tracing-cluster-kafka-bootstrap:9092
#             - name: KAFKA_REST_LISTENERS
#               value: 'http://0.0.0.0:8082'
#             - name: KAFKA_REST_HOST_NAME
#               value: 'tracing-cluster-rest-proxy'
#           resources:
#             limits:
#               memory: "128Mi"
#               cpu: "500m"
# ...


---
apiVersion: v1
kind: Service
metadata:
  name: tracing-cluster-rest-proxy
spec:
  type: ClusterIP
  selector:
    app: tracing-cluster-rest-proxy
  ports:
    - name: http
      protocol: "TCP"
      port: 8082
      targetPort: 8082
...


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-cluster-topics-ui
spec:
  selector:
    matchLabels:
      app: tracing-cluster-topics-ui
  template:
    metadata:
      labels:
        app: tracing-cluster-topics-ui
    spec:
      containers:
        - name: tracing-cluster-topics-ui
          image: landoop/kafka-topics-ui
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: KAFKA_REST_PROXY_URL
              value: http://tracing-cluster-bridge-service:8082/
            - name: PROXY
              value: "true"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
...


---
apiVersion: v1
kind: Service
metadata:
  name: tracing-cluster-topics-ui
spec:
  type: ClusterIP
  selector:
    app: tracing-cluster-topics-ui
  ports:
    - name: http
      protocol: "TCP"
      port: 8000
      targetPort: 8000
...


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-cluster-connect-ui
spec:
  selector:
    matchLabels:
      app: tracing-cluster-connect-ui
  template:
    metadata:
      labels:
        app: tracing-cluster-connect-ui
    spec:
      containers:
        - name: kafka-connect-ui
          image: landoop/kafka-connect-ui
          ports:
            - name: http-kc
              containerPort: 8000
          env:
            - name: CONNECT_URL
              value: http://tracing-cluster-connect-api:8083
            - name: PORT
              value: "8000"
            - name: PROXY
              value: "true"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
...


---
apiVersion: v1
kind: Service
metadata:
  name: tracing-cluster-connect-ui
spec:
  type: ClusterIP
  selector:
    app: tracing-cluster-connect-ui
  ports:
    - name: http
      protocol: "TCP"
      port: 8000
      targetPort: 8000
...
