apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


generatorOptions:
  disableNameSuffixHash: true


secretGenerator:
  - name: additional-scrape-configs
    files:
      - prometheus-additional.yaml


resources:
  - prometheus.yml
  - prometheus-rules.yml
  - roleConfig.yml
  - service-account.yml
  - service.yml
  - serviceMonitor.yml
  - serviceMonitorApiserver.yml
  - serviceMonitorCoreDNS.yml
  - serviceMonitorIstio.yml
  - serviceMonitorKubeControllerManager.yml
  - serviceMonitorKubelet.yml
  - serviceMonitorKubeScheduler.yml
