apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    prometheus: k8s
spec:
  type: ClusterIP
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
      protocol: TCP