apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  experimentation: bookinfo

namespace: default

bases:
  - ../common/

resources:
  - bookinfo.yaml
  - bookinfo-vs.yaml
