---
apiVersion: v1
kind: Service
metadata:
  name: itinerix-cluster-connect-ui
spec:
  type: ClusterIP
  selector:
    app: itinerix-cluster-connect-ui
  ports:
  - name: http-webui
    protocol: "TCP"
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itinerix-cluster-connect-ui

spec:
  selector:
    matchLabels:
      app: itinerix-cluster-connect-ui
  template:
    metadata:
      labels:
        app: itinerix-cluster-connect-ui
    spec:
      containers:
      - name: kafka-connect-ui
        image: landoop/kafka-connect-ui
        ports:
        - name: http-webui
          containerPort: 8000
        env:
        - name: CONNECT_URL
          value: http://itinerix-cluster-connect-api:8083
        - name: PORT
          value: "8000"
        - name: PROXY
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-connect-ui
spec:
  hosts: [ "*" ]
  gateways: [ tracegrapher-gateway ]
  http:
  - match:
    - uri:
        prefix: /kafka-connect
    rewrite:
      uri: /
    route:
    - destination:
        host: itinerix-cluster-connect-ui
        port:
          number: 8000
  - match:
    - uri:
        regex: /api/kafka-connect-([0-9]+)(/.*)
    route:
    - destination:
        host: itinerix-cluster-connect-ui
        port:
          number: 8000
---