apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases

secretGenerator:
  - name: grafana-env
    behavior: replace
    namespace: monitoring-stack
    env: grafana.env


patchesStrategicMerge:
  - prometheus-patch.yml
  - tracing-lb-patch.yml
