apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-collector
  labels:
    app: opencensus
    component: oc-collector
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      app: opencensus
      component: oc-collector
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        app: opencensus
        component: oc-collector
    spec:
      containers:
      - name: oc-collector
        image: omnition/opencensus-collector:0.1.11
        command:
        - "/occollector_linux"
        - "--config=/conf/oc-collector-config.yaml"
        env:
        - name: GOGC
          value: "80"
        ports:
        - containerPort: 8888
        - name: zipkin
          containerPort: 9411
        - name: c-tchan-thrft
          containerPort: 14267
        - name: c-binary-thrft
          containerPort: 14268
        - name: opencensus
          containerPort: 55678
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        volumeMounts:
        - name: oc-collector-config-vol
          mountPath: /conf
#        - name: oc-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
      - name: oc-collector-config-vol
        configMap:
          name: oc-collector-conf
          items:
          - key: oc-collector-config.yaml
            path: oc-collector-config.yaml
        