apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production

  storage:
    type: elasticsearch
    options:
      es:
        # use-aliases: true
        server-urls: http://jaeger-tracing-backend-es-http:9200
    secretName: elasticsearch-auth
    esIndexCleaner:
      enabled: false
      image: jaegertracing/jaeger-es-index-cleaner
      numberOfDays: 7
      schedule: "55 23 * * *"
    # esRollover:
    #   enabled: true
    #   conditions: "{\"max_age\": \"2d\"}"
    #   readTTL: 7d
    #   schedule: "55 23 * * *"

  query:
    options:
      query:
        base-path: /jaeger

  ui:
    options:
      dependencies:
        menuEnabled: false

  ingress:
    enabled: false
