apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne

  query:
    options:
      query:
        base-path: /jaeger

  ui:
    options:
      dependencies:
        menuEnabled: false

  ingress:
    enabled: false
