apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: jaeger-tracing-backend
  config:
    elasticsearch.ssl.verificationMode: none
    logging.quiet: true
    server:
      basePath: /kibana
      rewriteBasePath: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        # Rewrite Readiness probe bacause of Kibana Base Path
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /kibana/login
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
  http:
    tls:
      selfSignedCertificate:
        disabled: true
