apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: experimentation-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts: [ "*" ]
    port:
      number: 8080
      name: http2
      protocol: HTTP2
    