apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.4.2
  count: 1
  elasticsearchRef:
    name: jaeger-tracing-backend
  http:
    tls:
      selfSignedCertificate:
        disabled: true