apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
  labels:
    alertmanager: main
spec:
  selector:
    alertmanager: main
    app: alertmanager
  ports:
  - name: http-web
    port: 9093
    targetPort: 9093
  sessionAffinity: ClientIP