apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trace-grapher

configMapGenerator:
  - name: kubeconfig
    files:
      - sample-kubeconfig

bases:
  - neo4j
  - jupyter
  - kafka

resources:
  - gateway.yml