apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  experimentation: emojivoto

namespace: default

bases:
  - ../common/

resources:
  - emojivoto.yaml
  - emojivoto-vs.yaml
