---
apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
    - protocol: TCP
      name: https
      port: 443
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
...

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
  annotations:
    "sidecar.jaegertracing.io/inject": "true"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args: [
            '--api', '--api.insecure',
            '--log', '--accesslog',
            '--entrypoints.http.address=:80',
            '--entrypoints.https.address=:443',
            '--entrypoints.traefik.address=:8080',
            '--providers.kubernetescrd',
            '--metrics.prometheus',
            '--metrics.prometheus.entrypoint=traefik',
            '--tracing.jaeger',
            '--tracing.jaeger.samplingServerURL=http://localhost:5778/sampling',
            '--tracing.jaeger.samplingType=const',
            '--tracing.jaeger.samplingParam=1',
            '--tracing.jaeger.localAgentHostPort=localhost:6831',
          ]
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
...
