apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-cluster-connect-ui

spec:
  selector:
    matchLabels:
      app: tracing-cluster-connect-ui
  template:
    metadata:
      labels:
        app: tracing-cluster-connect-ui
    spec:
      containers:
        - name: kafka-connect-ui
          image: landoop/kafka-connect-ui
          ports:
            - name: http-kc
              containerPort: 8000
          env:
            - name: CONNECT_URL
              value: http://tracing-cluster-connect-api:8083
            - name: PORT
              value: "8000"
            - name: PROXY
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
