apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases

secretGenerator:
  - name: grafana-env
    behavior: replace
    namespace: monitoring-stack
    env: grafana.env


patchesStrategicMerge:
  - elasticsearch-tuning.yml
  - fluentd-tuning.yml
  - kafka-tuning.yml
