- module: kubernetes
  metricsets:
    - state_node
    - state_deployment
    - state_replicaset
    - state_pod
    - state_container
    - state_cronjob
    - state_resourcequota
    # Uncomment this to get k8s events:
    - event
  period: 10s
  host: ${NODE_NAME}
  hosts: ["kube-state-metrics:8080"]