# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
      - name: wait-frontend
        image: curlimages/curl
        command: ['sh', '-c', 'set -x; 
          until timeout 2 curl -f "http://${FRONTEND_ADDR}"; do 
            echo "waiting for http://${FRONTEND_ADDR}"; 
            sleep 2;
          done;']
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
      containers:
      - name: main
        image: gcr.io/opencensus-microservices-demo/loadgenerator@sha256:9049fedd3406a2a7257774cad340fc68e5f8bdc87342a5109acbaaeaa39b1735
        env:
        - name: FRONTEND_ADDR
          valueFrom:
            configMapKeyRef:
              name: loadgenerator-config
              key: FRONTEND_ADDR
        - name: USERS
          valueFrom:
            configMapKeyRef:
              name: loadgenerator-config
              key: USERS
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
