apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: omnition/opentelemetry-collector:v0.2.3
        command:
        - "/otelcol"
        - "--config=/conf/otel-collector-config.yaml"
        env:
        - name: GOGC
          value: "80"
        ports:
        - containerPort: 8888
        - name: zipkin
          containerPort: 9411
        - name: c-tchan-thrft
          containerPort: 14267
        - name: c-binary-thrft
          containerPort: 14268
        - name: opencensus
          containerPort: 55678
        resources:
          limits:
            cpu: "500"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
      - name: otel-collector-config-vol
        configMap:
          name: otel-collector-conf
          items:
          - key: otel-collector-config.yaml
            path: otel-collector-config.yaml
