apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-stack


configMapGenerator:
  - name: otel-collector-conf
    files:
      - configs/otel-collector-config.yaml


resources:
  - collector-deployment.yml
  - collector-service.yml
