# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: tcp-services
#   namespace: ingress-nginx
# data:
#   9411: "trace-grapher/jaeger-streaming-collector"
#   #14250: ""
#   #14267: ""
#   #14268: ""