apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases

secretGenerator:
  - name: neo4j-env
    behavior: replace
    namespace: trace-grapher
    env: neo4j.env

  - name: almond-env
    behavior: replace
    namespace: trace-grapher
    env: almond.env
 
patchesStrategicMerge:
  - almond-tuning.yml
  - neo4j-tuning.yml
