apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases

secretGenerator:
  - name: neo4j-env
    behavior: merge
    namespace: trace-grapher
    env: neo4j.env

  - name: jupyter-env
    behavior: merge
    namespace: trace-grapher
    env: jupyter.env

configMapGenerator:
  - name: kubeconfig
    behavior: replace
    files:
      - kube/config

patchesStrategicMerge:
  - jupyter-tuning.yml
  - neo4j-tuning.yml
  - kafka-tuning.yml
