apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases

secretGenerator:
  - name: neo4j-env
    behavior: replace
    namespace: trace-grapher
    env: neo4j.env

  - name: jupyter-env
    behavior: replace
    namespace: trace-grapher
    env: jupyter.env
 
patchesStrategicMerge:
  - jupyter-tuning.yml
  - neo4j-tuning.yml
