apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: monitoring-stack
  labels:
    name: prometheus-adapter
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    name: prometheus-adapter
