apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-stack

bases:
  - alertmanager
  - grafana
  - kube-state-metrics
  - metric-server
  - node-exporter
  - prometheus
  - prometheus-adapter
